# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: SprintBoot app

on:
  push:
    branches: [ "main","test_eci" ]
    paths:
      - "dockerfiles/**"
      - "workflows/maven.yml"

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
  checkqafeature:
    needs: one
    if: contains('${{github.ref_name}}', 'feature')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: "${{ github.head_ref }}"
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Cacheado de Maven para acelerar el despliegue
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: file-checks
        uses: ./.github/test/checks/
  automerge:
    needs: 'checkqafeature'
    runs-on: ubuntu-latest
    steps:
      - name: file-checks
        uses: ./.github/test/checks/
  checkqamerge:
    needs: 'automerge'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  buildapp:
    needs: 'checkqamerge'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "${{ github.base_ref }}"
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Cacheado de Maven para acelerar el despliegue
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: build
        uses: ./.github/build/buildapp/
  createimage:
    needs: 'buildapp'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "${{ github.base_ref }}"
      - name: login docker
        uses: ./.github/build/createimage
  scannerimage:
    needs: 'createimage'
    if: contains('${{github.base_name}}', 'develop')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "${{ github.base_ref }}"
      - name: login docker
        uses: ./.github/build/scannerimage
